### ISSUE TITLE
Bazel Federation (rules_python) fail on BuildKite

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel-federation#121]
https://buildkite.com/bazel/bazel-federation/builds/435#5f705d2f-3523-49e9-bf73-b296a6279af6
```
@rules_python//examples/boto:boto_test                                   FAILED in 3 out of 3 in 0.7s
```
Test log:
```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_buildkite/93edee54d3d38d81a5ece387f62d48b8/sandbox/darwin-sandbox/23/execroot/rules_python_federation_example/bazel-out/darwin-fastbuild/bin/external/rules_python/examples/boto/boto_test.runfiles/rules_python/examples/boto/boto_test.py", line 16, in <module>
    import unittest
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/__init__.py", line 60, in <module>
    from .async_case import IsolatedAsyncioTestCase
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/async_case.py", line 1, in <module>
    import asyncio
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/private/var/tmp/_bazel_buildkite/93edee54d3d38d81a5ece387f62d48b8/sandbox/darwin-sandbox/23/execroot/rules_python_federation_example/bazel-out/darwin-fastbuild/bin/external/rules_python/examples/boto/boto_test.runfiles/examples_boto_pypi__futures_3_3_0/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/private/var/tmp/_bazel_buildkite/93edee54d3d38d81a5ece387f62d48b8/sandbox/darwin-sandbox/23/execroot/rules_python_federation_example/bazel-out/darwin-fastbuild/bin/external/rules_python/examples/boto/boto_test.runfiles/examples_boto_pypi__futures_3_3_0/concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
```

This only happens on macOS.

**Comment by meteorcloudy** [comment]
https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/688

This is still failing with Bazel@HEAD

**Comment by aiuto** [comment]
Fixed by removing the boto_test.  It is not really portable.

Packages must really be responsible for making  `bazel test ...` work on all platforms.  If they have to resort to disabling some tests on some platforms, that becomes unsustainable if people want to test interoperability.
